"""09/06/25 del field reader_id from book model

Revision ID: 16a795c220f4
Revises: 160cc1ae4369
Create Date: 2025-06-09 20:07:43.222111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a795c220f4'
down_revision: Union[str, None] = '160cc1ae4369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_reader_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'reader_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_reader_id_fkey', 'books', 'users', ['reader_id'], ['id'])
    # ### end Alembic commands ###
