"""create associate table

Revision ID: 41a132b50086
Revises: 2861480ea657
Create Date: 2025-06-10 11:56:05.975633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a132b50086'
down_revision: Union[str, None] = '2861480ea657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associate_table',
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('reader_id', 'book_id')
    )
    op.drop_table('reader_books_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader_books_association',
    sa.Column('reader_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('books_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['books_id'], ['books.id'], name='reader_books_association_books_id_fkey'),
    sa.ForeignKeyConstraint(['reader_id'], ['users.id'], name='reader_books_association_reader_id_fkey')
    )
    op.drop_table('associate_table')
    # ### end Alembic commands ###
