"""correction2 models

Revision ID: d6780b60aa0b
Revises: b30abe32fccb
Create Date: 2025-06-05 21:22:52.840646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6780b60aa0b'
down_revision: Union[str, None] = 'b30abe32fccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'year_of_public',
               existing_type=postgresql.INTEGER(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('books', 'appended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'appended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('books', 'year_of_public',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
